### ISSUE TITLE
[Suggestion] better display name when insufficient width

### ISSUE THREAD

**Issue by CosticaPuntaru** [MoOx/atom-smart-tab-name#14]
i've added the fallowing css to make the names better for multiple tabs
it shrinks  the folder in so its visible but it dose not take to much space 

``` less
.smart-tab-name{
  overflow: hidden;
  direction: initial;
  display: flex;
  justify-content: center;

  .folder{
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
    flex-shrink: 3;
  }

  .file{
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
    flex-shrink: 1;
  }
}
```

if you do this i suggest breaking the file extension in to a different span so you can make that visible always, i use some plugin for icons and with that i don't care about the file extension
